# This file is used to build ZMK firmware for your keyboards.
# It uses the reusable ZMK workflow to handle the build process.
# For more information, see the ZMK documentation:
# https://zmk.dev/docs/user-setup

name: Build ZMK firmware

on: [push, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      # The `board` and `shield` values below must match the names of your
      # board and shield directories respectively.
      # The build-matrix is a JSON string.
      build-matrix: |
        { "include": [
          { "board": "nice_nano_v2", "shield": "handwired_tofu" }
        ] }